
- name: Ensure all dns records exist in Cloudflare (create or update)
  community.general.cloudflare_dns:
    zone: "{{ dns_zone }}"
    type: "{{ dns_entry.type }}"
    name: "{{ dns_entry.name }}"
    value: "{{ dns_entry.value }}"
    proxied: false
    api_token: "{{ cloudflare_api_token }}"
    state: present
  loop: "{{ dns_entries }}"
  loop_control:
    loop_var: dns_entry
  diff: true
  register: update_results