- name: Initialize cf_entries for this zone
  set_fact:
    cf_entries: []

- name: Fetch DNS records page by page
  uri:
    url: "{{ cloudflare_api_base }}/{{ zone_id }}/dns_records?per_page={{ per_page }}&page={{ item }}"
    method: GET
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    return_content: yes
  loop: "{{ range(1, max_pages + 1) | list }}"
  loop_control:
    loop_var: item
  register: page_results

- name: Append page results to cf_entries
  set_fact:
    cf_entries: "{{ cf_entries + page_results.results | map(attribute='json.result') | sum(start=[]) }}"

- name: Add zone records to all_cf_entries
  set_fact:
    all_cf_entries: "{{ all_cf_entries + [ { 'zone': zone_name, 'dns_entries': cf_entries } ] }}"